# Generated by Django 4.0.2 on 2023-04-29 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminAndSellers', '0005_remove_seller_mail_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_linked_user', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=55)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('noofsales', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminAndSellers.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=55)),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('contactNumber', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order_type', models.BooleanField()),
                ('image', models.TextField(blank=True, null=True)),
                ('block', models.TextField(blank=True, null=True)),
                ('landmark', models.TextField(blank=True, null=True)),
                ('delivery_status', models.TextField(blank=True, null=True)),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminAndSellers.seller')),
            ],
        ),
    ]
