# Generated by Django 4.0.2 on 2023-04-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
